export const BASERUNNING = {
  LEAGUE_AVG_SPRINT_SPEED: 27,
  SPEED_SCALE: 0.007,

  MIN_MULTIPLIER: 0.90,
  MAX_MULTIPLIER: 1.10,

  WEIGHT_BATTER_TO_FIRST: 1.0,
  WEIGHT_R1_TO_SECOND: 1.5,
  WEIGHT_R2_TO_THIRD: 2.0,
  WEIGHT_R3_SCORES: 4.0,
} as const;
