export const SITUATION = {
  INNING_LEVERAGE_MIN: 0.60,
  INNING_LEVERAGE_MAX: 1.45,

  WALK_OFF_BONUS: 0.20,

  LATE_INNING_CHALLENGE_URGENCY: 9,
  CHALLENGE_URGENCY_BONUS_WITH_TWO: 0.28,
  CHALLENGE_URGENCY_BONUS_WITH_ONE: 0.18,

  WALK_OFF_MAX_DEFICIT: -3,

  LATE_GAME_INNING: 7,
  CLOSE_GAME_MAX_RUN_DIFF: 2,
  BLOWOUT_MIN_RUN_DIFF: 5,

  RUN_DIFF_LEVERAGE_BY_GAP: [1.00, 0.95, 0.85, 0.72, 0.55] as const,
  RUN_DIFF_LEVERAGE_BLOWOUT: 0.35,

  WEIGHT_MIN: 0.30,
  WEIGHT_MAX: 1.90,
} as const;
