export const THRESHOLDS = {
  AUTO_ALLOW: 75,
  ALLOW: 50,
  WARN: 28,

  ALLOW_CONFIDENCE_ENTRY: 60,
  ALLOW_CONFIDENCE_EXIT: 25,

  WARN_CONFIDENCE_ENTRY: 85,
  WARN_CONFIDENCE_EXIT: 65,
} as const;
